import CryptoKit
import Foundation
import Security

/// Ed25519 public key matching the private key in `keys/license-priv.pem`.
/// Generated by `openssl genpkey -algorithm ed25519`. Safe to publish.
private let LICENSE_PUBKEY_BASE64 = "3MHQrdyHSeysvQQX0xMv7t7GOxgUnjvbx5BkGjz5BJc="

/// Decoded JWT body. The Stripe customer id and session id let us reissue
/// after refunds without trusting the client to identify itself.
struct LicensePayload: Codable {
    let iss: String
    let sub: String
    let aud: String
    let iat: Int
    let jti: String
    let entitlements: [String]
}

enum LicenseError: Error {
    case malformed
    case badSignature
    case badClaims
    case keychain(OSStatus)
}

enum LicenseVerifier {

    static func verify(_ jwt: String) throws -> LicensePayload {
        let parts = jwt.split(separator: ".")
        guard parts.count == 3 else { throw LicenseError.malformed }

        let signingInput = "\(parts[0]).\(parts[1])"
        guard let signingData = signingInput.data(using: .utf8),
              let signature   = base64urlDecode(String(parts[2])),
              let payloadJSON = base64urlDecode(String(parts[1])),
              let pubKeyData  = Data(base64Encoded: LICENSE_PUBKEY_BASE64)
        else { throw LicenseError.malformed }

        let pubKey = try Curve25519.Signing.PublicKey(rawRepresentation: pubKeyData)

        guard pubKey.isValidSignature(signature, for: signingData) else {
            throw LicenseError.badSignature
        }

        let payload = try JSONDecoder().decode(LicensePayload.self, from: payloadJSON)

        guard payload.iss == "d4mac.com",
              payload.aud == "d4mac-client"
        else { throw LicenseError.badClaims }

        return payload
    }

    static func store(_ jwt: String) throws {
        let data = Data(jwt.utf8)
        let q: [String: Any] = [
            kSecClass as String:         kSecClassGenericPassword,
            kSecAttrService as String:   "app.d4mac.license",
            kSecAttrAccount as String:   "default",
            kSecValueData as String:     data,
            kSecAttrAccessible as String: kSecAttrAccessibleAfterFirstUnlock,
        ]
        SecItemDelete(q as CFDictionary)
        let status = SecItemAdd(q as CFDictionary, nil)
        guard status == errSecSuccess else { throw LicenseError.keychain(status) }
    }

    static func loadStored() -> String? {
        let q: [String: Any] = [
            kSecClass as String:       kSecClassGenericPassword,
            kSecAttrService as String: "app.d4mac.license",
            kSecAttrAccount as String: "default",
            kSecReturnData as String:  true,
            kSecMatchLimit as String:  kSecMatchLimitOne,
        ]
        var item: CFTypeRef?
        guard SecItemCopyMatching(q as CFDictionary, &item) == errSecSuccess,
              let data = item as? Data,
              let s = String(data: data, encoding: .utf8)
        else { return nil }
        return s
    }

    static func clearStored() {
        let q: [String: Any] = [
            kSecClass as String:       kSecClassGenericPassword,
            kSecAttrService as String: "app.d4mac.license",
            kSecAttrAccount as String: "default",
        ]
        SecItemDelete(q as CFDictionary)
    }

    private static func base64urlDecode(_ s: String) -> Data? {
        var t = s.replacingOccurrences(of: "-", with: "+")
                 .replacingOccurrences(of: "_", with: "/")
        let pad = (4 - t.count % 4) % 4
        t.append(String(repeating: "=", count: pad))
        return Data(base64Encoded: t)
    }
}
